---
abstract: unknown
author:
  - 'Yuri Karaban <ykar@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-PageRank
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  URI::Escape: 0
version: 0.17
